applica/config/routes.rb
Rails.application.routes.draw do
  resources :publishes

end

applica/app/controllers/publishes_controller.rb
class PublishesController < ApplicationController
  def new
  end
  def create
   # @article = Publish.new(params.require(:publish).permit(:topic, :text))
    a =  params[:publis]
    b = a["topic"]
    c = a["text"]
    @article = Publish.new(topic: b,text: c)
    @article.save
    puts "@article"
    puts @article
    puts "@article end"
    render :show  #good
   # redirect_to @article
  end
  def show
    puts "params"
    puts params
    puts "params end"
    @article = Publish.find(params[:id])
  end
  def index
    @articles = Publish.all
  end
  def edit
    puts "edit"
    puts params  #this is from index pg <td><%= link_to 'Edit', edit_publish_path(article) %></td>
    puts "edit end"
    @pulish = Publish.find(params[:id]) #must @publish not @article. if we change hea to pulish it shud change even in edit form both places n in update .require
  end
  def update
    @article = Publish.find(params[:id])
     a =  params[:pulish]
    b = a["topic"]
    c = a["text"]
    @article.update(topic: b,text: c)
      render :show
  end
  
   def destroy
    @article = Publish.find(params[:id])
    @article.destroy
     redirect_to :action => "index"
  end
end

applica/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Applica</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

applica/app/views/publishes/edit.html.erb
<%= form_for :pulish, url: publish_path(@pulish), method: :put do |f| %>
  <p>
    <%= f.label :topic %><br>
    <%= f.text_field :topic %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

applica/app/views/publishes/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.topic %></td>
      <td><%= article.text %></td>
      <td><%= article %></td>
      <td><%= link_to 'show', publish_path(article) %></td>
      <td><%= link_to 'Edit', edit_publish_path(article) %></td>
      <td><%= link_to 'Destroy', publish_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New article', new_publish_path %>

applica/app/views/publishes/new.html.erb
<%= form_for :publis, url: publishes_path do |f| %>
 <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
 
  <div>
    <%= f.submit %>
  </div>
<% end %>

applica/app/views/publishes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.topic %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<%= link_to 'Show all', publishes_path %>