try/config/routes.rb
Rails.application.routes.draw do
  
  
  get '/publishes/:publish_id/author/new' => 'author#new'
  get '/publishes/:publish_id/comments/new' => 'comments#new',as: 'commentnew'
  post '/publishes/:publish_id/author' => 'author#create',as: 'authorcreate'
  post '/publishes/:publish_id/comments' => 'comments#create',as: 'commentcreate'
  get '/publishes' => 'publishes#index',as: 'index'
  get '/publishes/new' => 'publishes#new',as: 'new'
  post '/publishes/create' => 'publishes#create',as: 'create'
  get '/publishes/:id/edit' => 'publishes#edit',as: 'edit'
  get '/publishes/:id' => 'publishes#show',as: 'show'                             #,as: 'publish'
  put '/publishes/:id' => 'publishes#update',as: 'update'
  delete '/publishes/:id' => 'publishes#destroy',as: 'delete'

end

try/app/models/author.rb
class Author < ActiveRecord::Base
  belongs_to :publish
end

try/app/models/comm.rb
class Comm < ActiveRecord::Base
  belongs_to :publish
end

try/app/models/publish.rb
class Publish < ActiveRecord::Base
  has_one :author, dependent: :destroy
  has_many :comms, dependent: :destroy
end

try/app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def new
    puts "new1"
    puts params
    @publish = Publish.find(params[:publish_id])
    @author = @publish.build_author
    puts @publish 
    puts "new2"
  end
  def create
    puts params
    a = params[:author]
    b = a["name"]
    @publish = Publish.find(params[:publish_id])
    @author = @publish.create_author(name: b)
   # @author = @publish.build_author(name: b)
   # @author.save
    redirect_to :controller=>"publishes",:action => :index
  end
end

try/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
     @publish = Publish.find(params[:publish_id])
    @comments = @publish.comms.build
  end
  def create
    puts params
    a = params[:comm]
    b = a["name"]
    @publish = Publish.find(params[:publish_id])
    @author = @publish.comms.create(name: b)
    redirect_to :controller=>"publishes",:action => :show,:id=>params[:publish_id]
    
  end
end

try/app/controllers/post_controller.rb
class PostController < ApplicationController
end

try/app/controllers/postt_controller.rb
class PosttController < ApplicationController
end

try/app/controllers/publishes_controller.rb
class PublishesController < ApplicationController
  def new
  end
  def create
    a =  params[:publish]
    b = a["title"]
    c = a["text"]
    
    @article = Publish.new(title: b,text: c)
    @article.save
   # @article = Publish.find(1)
   # redirect_to :controller=>"publishes",:action => :show,:id=>@article.id  #first this
    redirect_to :controller=>"author",:action => :new,:publish_id=>@article.id
  end
  def show
     puts params
     @article = Publish.find(params[:id])
  end
  def index
    @publishes = Publish.all
  end
  def edit
    puts params
    @publish = Publish.find(params[:id])
  end
  def update
    puts "update"
    puts params
    puts "update2"
    @article = Publish.find(params[:id])
    puts "update3"
    puts @article
    puts "update4"
    a = params[:publish]
    b = a[:title]
    c = a[:text]
    puts a
    puts b
    puts c
    puts "update5"
    @article.update(title: b, text: c)
    redirect_to :controller=>"publishes",:action => :index
  end
  
  def destroy
    puts "destroy1"
    puts params
    @publish = Publish.find(params[:id])
    @publish.destroy
    redirect_to :controller=>"publishes",:action => :index
  end
end

try/app/helpers/author_helper.rb
module AuthorHelper
end

try/app/helpers/comments_helper.rb
module CommentsHelper
end

try/app/helpers/post_helper.rb
module PostHelper
end

try/app/helpers/postt_helper.rb
module PosttHelper
end

try/app/views/publishes/edit.html.erb
<%= form_for :publish, url: update_path(@publish), method: :put do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', index_path %>

try/app/views/publishes/index.html.erb
<h1>Listing publishes</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @publishes.each do |publish| %>
    <tr>
      <td><%= publish.title %></td>
      <td><%= publish.text %></td>
      <td><%= link_to "Edit", edit_path(publish) %></td>
      <td><%= link_to "Show", show_path(publish) %></td>
      <td><%= link_to "Delete", delete_path(publish), method: :delete, data: { confirm: 'Are you sure?' } %></td>      
    </tr>
  <% end %>
</table>
<%= link_to "New", new_path %>

try/app/views/publishes/new.html.erb
<%= form_for :publish, url: create_path do |f| %>


  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back", index_path %>

try/app/views/publishes/show.html.erb
<p>
  <% if @article.author != nil  %>
  <%= @article.author.name %>
    <% else %>
      <%= "Unknown Author" %>
<% end %>
</p>


<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<hr>
<p>
    <% @article.comms.each do |comment| %>
  
      <strong>Name of commenter: </strong>
      <%= comment.name %>
  <hr>
    <% end %>
</p>

<%= link_to 'Comment', commentnew_path(@article) %>
<%= link_to 'Back', index_path %>